### ISSUE TITLE
Multiple Progress Bars keep printing new lines

### ISSUE THREAD

**Issue by pranjalchaubey** [alphatwirl/atpbar#16]
Hi 
I am trying the simple two progress bars example, but my terminal is printing each bar on a newline. 
```
   for i in atpbar(range(4), name='outer'):
        n = random.randint(500, 1000)
        for j in atpbar(range(n), name='inner {}'.format(i)):
            time.sleep(0.0001)
```
![pbar](https://user-images.githubusercontent.com/23052833/76702186-eac0af00-66ed-11ea-9e40-8998d6361d36.png)
How to fix this problem?

**Comment by TaiSakuma** [comment]
Thank you for letting me know about the issue.

Would you mind also letting me know the OS, Python version, and Terminal app that you are using, please?

**Comment by pranjalchaubey** [comment]
hi Tai 
OS - Windows 10 
Python - 3.6
Terminal - CMD 

The code gives a similar output on the terminal running inside VS Code as well.

**Comment by SwapnilSoni1999** [comment]
even though after scrolling a new bar appears

**Comment by TaiSakuma** [comment]
Thank you for letting me know. I apologize for the delay. I don't have access to a windows machine at the moment and cannot test it. I will try when I can use Windows.

**Comment by SwapnilSoni1999** [comment]
Also there is issue on linux too. When the threads exceed size of terminal window, and when I scroll it  it duplicates printing of progress bars

**Comment by TaiSakuma** [comment]
@SwapnilSoni1999 I see. I think that that is a different issue. Would you mind creating a new issue?

**Comment by SwapnilSoni1999** [comment]
Sure sir i ll upload screen record if possible

**Comment by TaiSakuma** [comment]
@SwapnilSoni1999 Sounds great. Thank you.

**Comment by TaiSakuma** [comment]
@pranjalchaubey, I released the version [1.1.2](https://pypi.org/project/atpbar/1.1.2/).

I updated the escape code for controlling the cursor on the terminal.

This version might work on Windows although I haven't had a chance to test it because I didn't have a Windows machine.

**Comment by pranjalchaubey** [comment]
Thanks @TaiSakuma, I will check it out!

**Comment by TaiSakuma** [comment]
@pranjalchaubey, that is great. Thank you.

**Comment by udptcp** [comment]
Hi Tai,
for me it's not fixed on windows.
I am trying to run:
```
n = random.randint(1000, 10000)
for i in atpbar(range(n)):  
    time.sleep(0.00001)
```
And this is my result on windows CMD:

![grafik](https://user-images.githubusercontent.com/65719534/82565251-60c41500-9b7a-11ea-9a13-5e3193d209a8.png)

**Comment by TaiSakuma** [comment]
@udptcp, thank you for letting me know.

Would you mind letting me the version of Windows that you used? You wrote that you used "windows CMD". That is [Windows Console](https://en.wikipedia.org/wiki/Windows_Console), I assume.  I think that atpbar might work on [Windows Terminal](https://en.wikipedia.org/wiki/Windows_Terminal) because it seems to support ANSI escape code.

**Comment by udptcp** [comment]
Thanks @TaiSakuma 

I use Windows 10 LTSC version 1607 and tested with Windows Console. Windows Terminal needs at least version 1903 to work, so I can't check this out. 
But I have tried to connect via [PuTTY](https://en.wikipedia.org/wiki/PuTTY) to my machine and execute the script. This is the result:

![grafik](https://user-images.githubusercontent.com/65719534/82666500-56675100-9c36-11ea-94e1-9540e9de126a.png)

**Comment by TaiSakuma** [comment]
@udptcp, thank you for letting me know about Windows Terminal. I wasn't aware that it only works with recent versions of Windows 10.

Thank you also for the screenshot on PuTTY. It might work there if the terminal is a bit wider.  At the moment, atpbar doesn't work properly if the terminal width is less than 90 characters (I intend to fix it someday).

**Comment by johnnymads** [comment]
On Windows, you have to call SetConsoleMode with ENABLE_VIRTUAL_TERMINAL_PROCESSING (see https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#cursor-positioning). Doing so in python is explained here: https://stackoverflow.com/questions/36760127/how-to-use-the-new-support-for-ansi-escape-sequences-in-the-windows-10-console

I put 
import ctypes

kernel32 = ctypes.windll.kernel32
kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
at the top of my script and atpbar worked great in both cmd and powershell.

**Comment by johnnymads** [comment]
A much more robust version of the code is here: https://bugs.python.org/issue30075
